config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'

  # New
  get 'tasks/new', to: 'tasks#new'
  # Create
  post '/tasks', to: 'tasks#create'

  # Index
  get '/tasks', to: 'tasks#index'

  # Show
  get '/tasks/:id', to: "tasks#show", as: 'task'

  # Edit
  get 'tasks/:id/edit', to: "tasks#edit", as: 'task_edit'
  # Update
  patch 'tasks/:id', to: "tasks#update"

  # Destroy
  delete '/tasks/:id', to: "tasks#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(name: params[:name], description: params[:description], done: params[:done])
    task.save
    redirect_to task_path(task)
  end

  def edit
   @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(name: params[:name], description: params[:description], done: params[:done])
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<!--<%= form_for(@task) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.label :done %>
  <%= form.check_box :done %>
  <%= form.submit %>
<% end %>-->

<form action="/tasks/<%= @task.id %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" value="<%=@task.name%>">
  <input type="text" name="description" value="<%=@task.description%>">
  <input type="checkbox" name="done" value="<%=@task.done%>">
  <button>Update !</button>
</form>

app/views/tasks/index.html.erb
<div id="todo_list">
  <h1>My TODO List!</h1>
  <ul>
    <% @tasks.each do |task| %>
      <div id="task">
        <li>Done: <%= task.done %> - Name: <%= task.name %> - Description: <%= task.description %></li>
        <div id="task_button">
          <%= link_to "Show", task_path(task), class: "btn btn-info" %>
          <%= link_to "Edit", task_edit_path(task), class: "btn btn-warning"%>
          <%= link_to "Destroy", task_path(task), method: "delete", data: { confirm: "ARE YOU SUUUURE ?"}, class: "btn btn-danger" %>
        </div>
      </div>
    <% end %>
  </ul>
  <%= link_to "Create a new Task", tasks_new_path, class: "btn btn-success"%>
</div>

app/views/tasks/new.html.erb
<!--<%= form_for(@task) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :description %>
  <%= form.text_field :description %>
  <%= form.label :done %>
  <%= form.check_box :done %>
  <%= form.submit %>
<% end %>-->

<form action="<%= tasks_path %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Task name">
  <input type="text" name="description" placeholder="Task description">
  <input type="checkbox" name="done">
  <button>Create !</button>
</form>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<strong><%= @task.done %></strong>

<p><%= @task.description %></p>

<%= link_to "Index", tasks_path, class: "btn btn-success" %>